export type ServicePageData = {
  slug:string; name:string; eyebrow:string; title:string; description:string; image:string;
  intro:string; items:string[]; preparation:string; note?:string; faq:[string,string][];
};

export const servicePages: ServicePageData[] = [
 {slug:'moebelmontage',name:'Möbelmontage',eyebrow:'MÖBELMONTAGE IM SAARLAND',title:'Neue Möbel. Ohne Aufbaustress.',description:'Möbelmontage im Saarland: Kommoden, Regale, Sideboards und Wohnmöbel fachgerecht aufbauen lassen.',image:'g155.jpg',intro:'Vom einzelnen Sideboard bis zur Einrichtung mehrerer Räume übernehme ich den Aufbau Ihrer Möbel und richte Türen, Schubladen und Beschläge sorgfältig aus.',items:['Regale, Kommoden und Sideboards aufbauen','TV-Möbel und Wohnzimmerschränke montieren','Türen, Schubladen und Beschläge einstellen','Wandbefestigungen nach Herstellerangaben abstimmen'],preparation:'Senden Sie Produktlinks oder Aufbauanleitungen, Anzahl der Möbel und Fotos des Aufstellorts.',faq:[['Können mehrere Möbel an einem Termin aufgebaut werden?','Ja. Eine vollständige Möbelliste hilft, Zeitbedarf und Umfang vorab abzustimmen.'],['Welche Hersteller montieren Sie?','IKEA und Möbel anderer Hersteller nach Prüfung von Modell und Anleitung.']]},
 {slug:'ikea-moebelmontage',name:'IKEA Möbelmontage',eyebrow:'IKEA MÖBELMONTAGE IM SAARLAND',title:'Ihr IKEA Einkauf. Fertig aufgebaut.',description:'IKEA Möbelmontage für KALLAX, BESTÅ, MALM, HEMNES, PAX und weitere Serien.',image:'g09.jpg',intro:'Sie wählen Ihre IKEA Möbel aus. Ich übernehme Aufbau, Ausrichtung und die Montage der vorgesehenen Beschläge.',items:['KALLAX, BILLY und BESTÅ montieren','MALM und HEMNES aufbauen','IKEA PAX inklusive Innenausstattung montieren','Mehrere Möbel in einem Auftrag koordinieren'],preparation:'Artikelnummern, Bestellübersicht oder Planungscode und ein Foto des Raums reichen für die erste Einschätzung.',faq:[['Montieren Sie auch IKEA PAX?','Ja. PAX ist Teil der IKEA Möbelmontage; für Suchende bleibt zusätzlich eine ausführliche PAX-Seite erreichbar.'],['Sind Sie offizieller IKEA Partner?','Nein. Andrii Ryndia Solutions ist ein unabhängiger Montageservice.']]},
 {slug:'pax-montage',name:'IKEA PAX Montage',eyebrow:'IKEA PAX MONTAGE IM SAARLAND',title:'Ein Platz für alles. Bis ins Detail.',description:'PAX Korpusse, KOMPLEMENT Innenausstattung sowie Dreh- und Schiebetüren montieren lassen.',image:'g132.jpg',intro:'Korpusse, Innenausstattung, Türen, Raumhöhe und Wandbefestigung müssen zusammenpassen. Ich montiere Ihre geplante Kombination und richte sie aus.',items:['PAX Korpusse und Eckkombinationen','KOMPLEMENT Schubladen, Böden und Stangen','Dreh- und Schiebetüren montieren','Platzverhältnisse und Kippsicherung abstimmen'],preparation:'Senden Sie PAX-Plan oder Planungscode, Schrankhöhe, Deckenhöhe und ein Foto des Raums.',faq:[['Was benötigen Sie für ein Angebot?','Den PAX-Plan, Montageort, Raumhöhe und möglichst ein Foto des Aufstellorts.'],['Ist PAX bei niedriger Decke möglich?','Das hängt von Schrankhöhe, Modell und verfügbarer Montagehöhe ab und wird vorab geprüft.']]},
 {slug:'kuechenmontage',name:'Küchenmontage',eyebrow:'KÜCHENMONTAGE IM SAARLAND',title:'Ihre Küche. Sorgfältig montiert.',description:'Mechanische Küchenmontage im Saarland: Schränke, Fronten, Sockel und Arbeitsplatten nach Absprache.',image:'g43.jpg',intro:'Eine Küche soll im Alltag funktionieren. Ich unterstütze Sie bei der mechanischen Montage Ihrer Planung und achte auf Ausrichtung und saubere Übergänge.',items:['Unter-, Ober- und Hochschränke montieren','Schränke ausrichten und verbinden','Fronten, Schubladen, Griffe und Sockel','Arbeitsplatten und Ausschnitte nach Absprache'],preparation:'Bitte senden Sie Küchenplan, Maße, Hersteller, Raumfotos und den gewünschten Montageumfang.',note:'Elektro-, Gas- und Wasseranschlüsse werden separat mit entsprechend qualifizierten Fachbetrieben geklärt.',faq:[['Montieren Sie auch IKEA Küchen?','Ja, nach Prüfung von Küchenplan, Raummaßen und gewünschtem Umfang.'],['Sind Geräteanschlüsse enthalten?','Anschlussarbeiten sind nicht pauschal enthalten und werden separat geklärt.']]},
 {slug:'schrankmontage',name:'Schrankmontage',eyebrow:'SCHRANKMONTAGE IM SAARLAND',title:'Mehr Ordnung. Sauber aufgebaut.',description:'Kleider-, Dreh- und Schiebetürschränke fachgerecht montieren und einstellen lassen.',image:'g124.jpg',intro:'Ich montiere Ihren Schrank, setze die Innenausstattung ein und stelle Türen und Schubladen ein.',items:['Kleider- und Garderobenschränke','Dreh- und Schiebetüren','Einlegeböden, Stangen und Schubladen','Ausrichtung und Kippsicherung'],preparation:'Hilfreich sind Hersteller, Modell, Maße, Türsystem, Raumhöhe und Etage.',faq:[['Montieren Sie andere Hersteller?','Ja, nach Prüfung des Modells und der vorhandenen Anleitung.'],['Wird der Schrank gesichert?','Vorgesehene Kippsicherungen werden passend zu Anleitung und Wandaufbau abgestimmt.']]},
 {slug:'bettmontage',name:'Bettmontage',eyebrow:'BETTMONTAGE IM SAARLAND',title:'Aufgebaut. Für Ihren Feierabend.',description:'Einzel-, Doppel-, Tages- und Stauraumbetten nach Anleitung montieren lassen.',image:'g030.jpg',intro:'Ich montiere Bettgestell, Lattenrost, Schubladen und vorgesehene Stauraumelemente und kontrolliere die Verbindungen.',items:['Einzel- und Doppelbetten','Tages- und Stauraumbetten','Lattenroste und Schubladen','Beschläge und Verbindungen kontrollieren'],preparation:'Senden Sie Modell, Produktlink, Bettgröße und Informationen zu Schubladen oder Stauraummechanik.',faq:[['Bauen Sie HEMNES, MALM und SLÄKT auf?','Ja. Bitte senden Sie das genaue Modell.'],['Montieren Sie Etagenbetten?','Nach Prüfung von Modell, Raumhöhe und Herstellerhinweisen.']]},
 {slug:'bueromoebelmontage',name:'Büromöbelmontage',eyebrow:'BÜROMÖBELMONTAGE IM SAARLAND',title:'Ihr Arbeitsplatz. Bereit für Ideen.',description:'Schreibtische, Rollcontainer, Regale und Büroschränke für Büro und Homeoffice montieren.',image:'g248.jpg',intro:'Vom Homeoffice bis zu mehreren Arbeitsplätzen baue ich Schreibtische und Stauraummöbel nach abgestimmter Reihenfolge auf.',items:['Schreibtische und Kombinationen','Rollcontainer und Büroschränke','Regale und Stauraum','Mehrere Arbeitsplätze koordinieren'],preparation:'Senden Sie Möbelliste, Stückzahlen, Produktlinks, Zugang und mögliche Montagezeiten.',faq:[['Sind mehrere Arbeitsplätze möglich?','Ja, nach Abstimmung von Stückzahl, Modellen und Zeitfenster.'],['Montieren Sie höhenverstellbare Tische?','Der mechanische Aufbau ist nach Prüfung des Modells möglich.']]},
];

export type RegionPageData={slug:string;name:string;districts:string[];arrival:string;localNote:string;image:string;projectTitle:string;focus:string[]};
export const regionPages:RegionPageData[]=[
 {slug:'saarbruecken',name:'Saarbrücken',districts:['St. Johann','Alt-Saarbrücken','Malstatt','Dudweiler'],arrival:'Kurze Wege vom Standort in Saarbrücken. Etage, Aufzug und Parkmöglichkeit bitte bei der Anfrage nennen.',localNote:'In dicht bebauten Stadtteilen hilft ein Foto von Hauseingang und Treppenhaus bei der Planung großer Schränke.',image:'gallery-hero.jpg',projectTitle:'PAX-Kombination als passendes Projektbeispiel',focus:['IKEA PAX','Küchen','Wohnmöbel']},
 {slug:'voelklingen',name:'Völklingen',districts:['Stadtmitte','Geislautern','Ludweiler','Wehrden'],arrival:'Die Anfahrt wird über die A620 oder die passende lokale Strecke abgestimmt. Postleitzahl und vollständige Möbelliste genügen für die Planung.',localNote:'Bei mehreren Räumen legen wir vorab eine sinnvolle Reihenfolge für den Aufbau fest.',image:'g09.jpg',projectTitle:'IKEA Regalsystem als passendes Projektbeispiel',focus:['IKEA Möbel','Schränke','Betten']},
 {slug:'saarlouis',name:'Saarlouis',districts:['Innenstadt','Roden','Fraulautern','Beaumarais'],arrival:'Anfahrt und Termin werden anhand der Adresse abgestimmt. Für Küchen sind Raumfotos und der vollständige Küchenplan besonders wichtig.',localNote:'Bitte teilen Sie mit, ob der Raum frei ist und die Pakete bereits am Aufbauort stehen.',image:'g43.jpg',projectTitle:'Küchenaufbau als passendes Projektbeispiel',focus:['Küchen','Wohnmöbel','Büro']},
 {slug:'homburg',name:'Homburg',districts:['Innenstadt','Erbach','Jägersburg','Kirrberg'],arrival:'Für Einsätze Richtung Homburg wird die Anfahrt zusammen mit Umfang und Zeitfenster geplant.',localNote:'Bei großen Schränken benötigen wir Raumhöhe, Stellmaß und den bestätigten Liefertermin.',image:'g132.jpg',projectTitle:'Große Schrankkombination als Projektbeispiel',focus:['IKEA PAX','Betten','Homeoffice']},
 {slug:'neunkirchen',name:'Neunkirchen',districts:['Innenstadt','Wellesweiler','Furpach','Wiebelskirchen'],arrival:'Die genaue Adresse und der Lieferumfang bestimmen die Terminplanung. Eine komplette Bestellübersicht vermeidet fehlende Zusatzteile.',localNote:'Türen, Schubladen und Wandaufhängungen bitte in der Möbelliste mit aufführen.',image:'g155.jpg',projectTitle:'Wohnmöbelmontage als passendes Projektbeispiel',focus:['IKEA Möbel','Wohnmöbel','Schränke']},
 {slug:'st-ingbert',name:'St. Ingbert',districts:['Mitte','Rohrbach','Hassel','Rentrisch'],arrival:'Montagezeiten und Zugang werden für Wohnung, Homeoffice oder Gewerberäume individuell abgestimmt.',localNote:'Bei Büromöbeln helfen ein Stellplan und die gewünschte Reihenfolge der Arbeitsplätze.',image:'g248.jpg',projectTitle:'Homeoffice-Arbeitsplatz als Projektbeispiel',focus:['Büromöbel','Schränke','Wohnmöbel']},
 {slug:'merzig',name:'Merzig',districts:['Innenstadt','Besseringen','Brotdorf','Hilbringen'],arrival:'Für Merzig werden Anfahrt und Zeitbedarf vor dem Termin gemeinsam geklärt. Bitte genaue Postleitzahl und Möbelliste senden.',localNote:'Bei umfangreichen Aufträgen helfen Fotos aller vorgesehenen Räume.',image:'g124.jpg',projectTitle:'Kleiderschrank als passendes Projektbeispiel',focus:['Schränke','Betten','IKEA Möbel']},
 {slug:'zweibruecken',name:'Zweibrücken',districts:['Mitte','Niederauerbach','Ixheim','Rimschweiler'],arrival:'Zweibrücken liegt in Rheinland-Pfalz. Anfahrt und Terminverfügbarkeit werden deshalb individuell vereinbart.',localNote:'Für eine verlässliche Einschätzung benötigen wir Adresse, Produktliste und gewünschten Zeitraum.',image:'gallery-3.jpg',projectTitle:'Bettmontage als passendes Projektbeispiel',focus:['IKEA Möbel','Küchen','IKEA PAX']},
];

export const routeSlugs=[...servicePages.map(x=>x.slug),...regionPages.map(x=>'moebelmontage-'+x.slug),'leistungen','regionen','gewerbekunden','referenzen','ueber-uns','kontakt','impressum','datenschutz','agb'];
