import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { whatsappUrl } from '../src/lib/site.ts';
import { regionPages, routeSlugs, servicePages } from '../src/lib/page-content.ts';

const routes=['',...routeSlugs];
const read=slug=>fs.readFileSync(path.join('dist',slug,'index.html'),'utf8');

test('all public pages are generated by one Next.js application',()=>{
 assert.equal(routes.length,25);
 for(const slug of routes){
  const html=read(slug);
  assert.equal((html.match(/<h1(?:\s|>)/g)||[]).length,1,slug||'/');
  assert.ok(html.includes('/_next/static/css/'),slug||'/');
  assert.ok(!html.includes('/css/site.css'),slug||'/');
  assert.ok(!html.includes('/js/site.js'),slug||'/');
  assert.ok(html.includes('info@saarmontage.de'),slug||'/');
  assert.ok(html.includes('id="cookie-panel"'),slug||'/');
  assert.ok(html.includes('content="noindex, nofollow"'),slug||'/');
 }
});

test('all local links and images resolve inside the exported site',()=>{
 for(const slug of routes){
  const html=read(slug);
  for(const match of html.matchAll(/(?:href|src)="([^"#?]+)[^"]*"/g)){
   const href=match[1];
   if(!href.startsWith('/'))continue;
   const pathname=decodeURIComponent(new URL(href,'https://saarmontage.de/'+slug).pathname);
   const target=path.join('dist',pathname,pathname.endsWith('/')?'index.html':'');
   assert.ok(fs.existsSync(target),`${slug||'/'} -> ${href}`);
  }
 }
});

test('regional landing pages contain unique local and project information',()=>{
 assert.equal(new Set(regionPages.map(page=>page.image)).size,regionPages.length);
 for(const page of regionPages){
  const html=read('moebelmontage-'+page.slug).replaceAll('<!-- -->','');
  for(const district of page.districts)assert.ok(html.includes(district),`${page.name}: ${district}`);
  assert.ok(html.includes(page.arrival),`${page.name}: arrival`);
  assert.ok(html.includes(page.localNote),`${page.name}: local note`);
  assert.ok(html.includes('/assets/'+page.image),`${page.name}: photo`);
  assert.ok(html.includes(page.projectTitle),`${page.name}: project example`);
 }
});

test('services have unique titles, descriptions, scope and preparation',()=>{
 const titles=new Set();
 for(const page of servicePages){
  const html=read(page.slug);
  assert.ok(!titles.has(page.title));titles.add(page.title);
  assert.ok(html.includes(page.description));
  assert.ok(html.includes(page.preparation));
  for(const item of page.items)assert.ok(html.includes(item),`${page.slug}: ${item}`);
 }
});

test('Open Graph image is a 1200 by 630 PNG and is linked on every page',()=>{
 const image=fs.readFileSync('dist/opengraph-image');
 assert.equal(image.subarray(1,4).toString(),'PNG');
 assert.equal(image.readUInt32BE(16),1200);
 assert.equal(image.readUInt32BE(20),630);
 for(const slug of routes){const html=read(slug);assert.ok(html.includes('property="og:image"'));assert.ok(html.includes('content="1200"'));assert.ok(html.includes('content="630"'));}
});

test('homepage JavaScript stays below the former 707 KB budget and contains no framer-motion',()=>{
 const html=read('');
 const scripts=[...html.matchAll(/<script[^>]+src="([^"?]+)[^"]*"/g)].map(match=>match[1]).filter(src=>src.startsWith('/'));
 const bytes=scripts.reduce((sum,src)=>sum+fs.statSync(path.join('dist',src)).size,0);
 assert.ok(bytes<650_000,`homepage scripts: ${bytes} bytes`);
 assert.ok(!fs.readFileSync('package-lock.json','utf8').includes('framer-motion'));
});

test('contact form documents Web3Forms and includes layered spam protection',()=>{
 const html=read('kontakt');
 const source=fs.readFileSync('src/components/ContactForm.tsx','utf8');
 const privacy=read('datenschutz');
 for(const label of ['IKEA Möbelmontage (inkl. PAX)','Demontage &amp; Wiederaufbau','Mehrere Möbel / Kompletteinrichtung','Gewerblicher Auftrag / Baumarkt','Sonstiges'])assert.ok(html.includes(label),label);
 assert.ok(html.includes('name="botcheck"'));
 assert.ok(source.includes('openedAt'));
 assert.ok(source.includes('sm-form-submissions'));
 assert.ok(source.includes('NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY'));
 assert.ok(privacy.includes('Web3Forms'));
});

test('WhatsApp text preserves service, city and the source page',()=>{
 const url=new URL(whatsappUrl({service:'Küchenmontage',city:'Saarbrücken',page:'/kuechenmontage/',code:'SM-TEST123'}));
 const message=url.searchParams.get('text');
 assert.equal(url.hostname,'wa.me');
 assert.ok(message.includes('Küchenmontage'));
 assert.ok(message.includes('Saarbrücken'));
 assert.ok(message.includes('Quelle: saarmontage.de/kuechenmontage/'));
 assert.ok(message.includes('SM-TEST123'));
});
