import Image from 'next/image';
import gallery from '../../content/gallery.json';
import { notFound } from 'next/navigation';
import { Header } from './Header';
import { Footer } from './Footer';
import { Contact } from './Contact';
import { ContactForm } from './ContactForm';
import { WhatsAppButton } from './WhatsAppButton';
import { ResponsivePhoto } from './ResponsivePhoto';
import { ServiceArea } from './ServiceArea';
import { ArrowIcon, CheckIcon, PinIcon } from './Icons';
import { serviceItems, locations, site } from '@/lib/site';
import { regionPages, servicePages } from '@/lib/page-content';

function Breadcrumbs({label,parent}:{label:string;parent?:{href:string;label:string}}){return <nav className="breadcrumbs-next container" aria-label="Brotkrumennavigation"><a href="/">Startseite</a><span>/</span>{parent&&<><a href={parent.href}>{parent.label}</a><span>/</span></>}<span aria-current="page">{label}</span></nav>}
function PageHero({eyebrow,title,text,image,service,city}:{eyebrow:string;title:string;text:string;image:string;service:string;city?:string}){return <section className="inner-hero section"><div className="container inner-hero-grid"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="inner-lead">{text}</p><div className="hero-actions"><WhatsAppButton inquiry={{service,city}}>Projekt anfragen</WhatsAppButton><a className="button button-secondary" href="/referenzen/">Arbeiten ansehen <ArrowIcon/></a></div><p className="inner-location"><PinIcon/>{city||'Saarland'} · Termin nach persönlicher Abstimmung</p></div><div className="inner-hero-photo"><ResponsivePhoto file={image} alt={`${service} – Originalfoto einer ausgeführten Arbeit`} sizes="(max-width:767px) calc(100vw - 32px), 48vw" eager/></div></div></section>}
function Faq({items}:{items:[string,string][]}){return <section className="section inner-soft"><div className="container inner-faq"><div><p className="eyebrow">GUT ZU WISSEN</p><h2>Klare Antworten<br/>vor dem Aufbau.</h2></div><div className="faq-list">{items.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>}
function Cta({service,city}:{service:string;city?:string}){return <section className="inner-cta section"><div className="container inner-cta-row"><div><p className="eyebrow">IHR PROJEKT</p><h2>Sie haben den Plan.<br/>Ich bringe das Werkzeug.</h2><p>Ein Foto oder Produktlink genügt für den ersten Schritt.</p></div><WhatsAppButton inquiry={{service,city}}>Details per WhatsApp senden</WhatsAppButton></div></section>}

function ServicePage({slug}:{slug:string}){const data=servicePages.find(x=>x.slug===slug);if(!data)notFound();const photos=gallery.filter(photo=>photo.category===({kuechenmontage:'kuechen','pax-montage':'pax',schrankmontage:'schraenke',bettmontage:'betten',bueromoebelmontage:'buero'}[slug]||'moebel')).slice(0,3);return <><Breadcrumbs label={data.name} parent={{href:'/leistungen/',label:'Leistungen'}}/><PageHero eyebrow={data.eyebrow} title={data.title} text={data.intro} image={data.image} service={data.name}/><section className="section"><div className="container scope-grid"><div><p className="eyebrow">LEISTUNGSUMFANG</p><h2>Was ich für Sie übernehme.</h2><ul className="feature-list">{data.items.map(item=><li key={item}><CheckIcon/>{item}</li>)}</ul>{data.note&&<p className="service-note">{data.note}</p>}</div><aside className="prep-card"><span>Vorbereitung</span><h3>Damit ich passend planen kann.</h3><p>{data.preparation}</p></aside></div></section><section className="section inner-gallery"><div className="container"><div className="section-heading"><div><p className="eyebrow">ORIGINALFOTOS</p><h2>Einblicke in die Montage.</h2></div><a href="/referenzen/" className="text-link">Alle Referenzen <ArrowIcon/></a></div><div className="inner-photo-grid">{photos.map(photo=><figure key={photo.file}><div><ResponsivePhoto file={photo.file} alt={photo.alt} sizes="(max-width:767px) calc(100vw - 32px), 33vw"/></div><figcaption>{photo.alt}</figcaption></figure>)}</div></div></section><Faq items={data.faq}/><Cta service={data.name}/></>}

function RegionPage({slug}:{slug:string}){const data=regionPages.find(x=>x.slug===slug);if(!data)notFound();return <><Breadcrumbs label={data.name} parent={{href:'/regionen/',label:'Regionen'}}/><PageHero eyebrow={`MÖBELMONTAGE ${data.name.toUpperCase()}`} title={`Möbelmontage in ${data.name}.`} text={`Persönlicher Möbel- und Küchenaufbau in ${data.name} und den umliegenden Stadtteilen.`} image={data.image} service="Möbelmontage" city={data.name}/><section className="section"><div className="container local-grid"><div><p className="eyebrow">VOR ORT</p><h2>Unterwegs in {data.name}.</h2><p>Zum Servicegebiet gehören unter anderem:</p><ul className="district-list">{data.districts.map(x=><li key={x}>{x}</li>)}</ul><p className="local-note">{data.localNote}</p></div><article className="local-project"><div className="local-project-photo"><ResponsivePhoto file={data.image} alt={`${data.projectTitle} für Anfragen aus ${data.name}`} sizes="(max-width:767px) calc(100vw - 32px), 45vw"/></div><div><small>PROJEKTBEISPIEL AUS DEM PORTFOLIO</small><h3>{data.projectTitle}</h3><p>Das Foto zeigt eine tatsächlich ausgeführte Montage und dient als Beispiel für vergleichbare Anfragen aus {data.name}.</p></div></article></div></section><section className="section inner-soft"><div className="container arrival-grid"><div><p className="eyebrow">ANFAHRT & PLANUNG</p><h2>Vor dem Termin geklärt.</h2><p>{data.arrival}</p></div><div><p className="eyebrow">HÄUFIG ANGEFRAGT</p><div className="focus-tags">{data.focus.map(x=><span key={x}>{x}</span>)}</div></div></div></section><Cta service="Möbelmontage" city={data.name}/></>}

function ServicesOverview(){return <><Breadcrumbs label="Leistungen"/><section className="page-intro-next section"><div className="container"><p className="eyebrow">UNSERE LEISTUNGEN</p><h1>Für jeden Raum.<br/>Der passende Aufbau.</h1><p>Wählen Sie die passende Leistung und senden Sie anschließend Produktlinks, Fotos oder Ihre Planung.</p></div></section><section className="section"><div className="container overview-grid">{serviceItems.map(s=><a key={s.slug} href={`/${s.slug}/`} className="overview-card"><div><ResponsivePhoto file={s.image} alt={`${s.name} – Originalfoto`} sizes="(max-width:767px) calc(100vw - 32px), 33vw"/></div><span>{s.label}</span><h2>{s.name}<ArrowIcon/></h2><p>{s.text}</p></a>)}</div></section><Cta service="Möbelmontage"/></>}
function RegionsOverview(){return <><Breadcrumbs label="Regionen"/><section className="page-intro-next section"><div className="container"><p className="eyebrow">SERVICEGEBIET</p><h1>Im Saarland zu Hause.<br/>Bei Ihnen im Einsatz.</h1><p>Acht eigene Ortsseiten mit Informationen zur Anfahrt und Vorbereitung.</p></div></section><ServiceArea/></>}

function PartnerPage(){const photos=['partner-baumarkt-10.png','partner-baumarkt-01.png','partner-baumarkt-08.png','partner-baumarkt-04.png','partner-baumarkt-07.png','partner-baumarkt-02.png'];return <><Breadcrumbs label="Für Geschäftskunden"/><PageHero eyebrow="B2B · BAUMARKT & HANDEL" title="Verkaufsflächen. Sauber organisiert." text="Andrii Ryndia Solutions unterstützt Baumärkte, Fachmärkte und Handelspartner bei praktischen Arbeiten auf der Verkaufsfläche." image={photos[0]} service="Marktservice für Geschäftskunden"/><section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">ERFAHRUNG IM MARKT</p><h2>Wobei wir Sie unterstützen.</h2></div><p>Aufbau von Waren- und Präsentationsständen, Sortierung und strukturierte Platzierung von Produkten sowie Umgestaltung von Verkaufsflächen.</p></div><div className="inner-photo-grid">{photos.map((file,i)=><figure key={file}><div><ResponsivePhoto file={file} alt={`Ausgeführte Baumarkt-Arbeit ${i+1}`} sizes="(max-width:767px) calc(100vw - 32px), 33vw"/></div><figcaption>Originalfoto aus einem durchgeführten Auftrag</figcaption></figure>)}</div></div></section><Cta service="Marktservice für Geschäftskunden"/></>}

function ReferencesPage(){const groups=[['kuechen','Küchen'],['pax','IKEA PAX'],['schraenke','Schränke'],['betten','Betten'],['buero','Büro & Homeoffice'],['moebel','Wohnmöbel']];return <><Breadcrumbs label="Referenzen"/><section className="page-intro-next section"><div className="container"><p className="eyebrow">UNSERE ARBEITEN</p><h1>Vom Karton<br/>zum fertigen Zuhause.</h1><p>Originalfotos aus dem Montagealltag, übersichtlich nach Möbelart geordnet.</p></div></section>{groups.map(([id,label])=><section className="section reference-group" id={id} key={id}><div className="container"><h2>{label}</h2><div className="reference-grid">{gallery.filter(x=>x.category===id).map(photo=><figure key={photo.file}><div><ResponsivePhoto file={photo.file} alt={photo.alt} sizes="(max-width:599px) calc(100vw - 32px), (max-width:999px) 50vw, 25vw"/></div><figcaption>{photo.alt}</figcaption></figure>)}</div></div></section>)}</>}
function AboutPage(){return <><Breadcrumbs label="Über mich"/><section className="section"><div className="container about-page-next"><Image src="/assets/andrii-photo.jpg" alt="Andrii Ryndia" width={620} height={760}/><div><p className="eyebrow">ANDRII RYNDIA SOLUTIONS</p><h1>Ein Ansprechpartner.<br/>Von Anfang bis Aufbau.</h1><p className="inner-lead">Hallo, ich bin Andrii. Unter Saarmontage.de finden Sie meinen persönlichen Montage- und Marktservice.</p><p>Sie stimmen Ihr Projekt direkt mit dem Menschen ab, der Ihre Möbel aufbaut. Produktlinks, Fotos und Pläne helfen mir, Umfang und Termin realistisch einzuschätzen.</p><ul className="feature-list"><li><CheckIcon/>Persönliche Abstimmung</li><li><CheckIcon/>Direkter Kontakt</li><li><CheckIcon/>Sorgfältiger Aufbau nach Anleitung</li></ul></div></div></section><Cta service="Möbelmontage"/></>}
function ContactPage(){return <><Breadcrumbs label="Kontakt"/><section className="page-intro-next section contact-page-intro"><div className="container"><p className="eyebrow">DIREKTER KONTAKT</p><h1>Montage anfragen.<br/>Persönlich antworten lassen.</h1><p>Beschreiben Sie kurz Ihr Projekt. Ein Foto, Produktlink oder Plan hilft bei der ersten Einschätzung.</p></div></section><Contact/></>}
function LegalPage({slug}:{slug:string}){const data={impressum:{title:'Impressum',body:<><h2>Angaben gemäß § 5 DDG</h2><p>Andrii Ryndia Solutions · Saarmontage.de<br/>Fischbachstraße 70<br/>66113 Saarbrücken<br/>Deutschland</p><h2>Kontakt</h2><p>Telefon: <a href={`tel:${site.phone.replaceAll(' ','')}`}>{site.phone}</a><br/>E-Mail: <a href={`mailto:${site.email}`}>{site.email}</a></p><h2>Verantwortlich für den Inhalt</h2><p>Andrii Ryndia, Anschrift wie oben.</p></>},agb:{title:'AGB & Auftragsinformationen',body:<><h2>Individuelle Vereinbarung</h2><p>Über diese Website wird kein Vertrag automatisch geschlossen. Leistung, Preis, Anfahrt und Termin werden für jedes Projekt persönlich abgestimmt.</p><h2>Leistungsumfang</h2><p>Besondere Anpassungen sowie Elektro-, Gas- und Wasserarbeiten müssen ausdrücklich und gegebenenfalls mit qualifizierten Fachbetrieben vereinbart werden.</p></>},datenschutz:{title:'Datenschutzerklärung',body:<><h2>1. Verantwortlicher</h2><p>Andrii Ryndia, Fischbachstraße 70, 66113 Saarbrücken. E-Mail: {site.email}.</p><h2>2. Hosting</h2><p>Beim Seitenaufruf verarbeitet der Hostinganbieter technische Verbindungsdaten zur sicheren Bereitstellung der Website.</p><h2>3. Kontaktformular und Web3Forms</h2><p>Bei E-Mail-Versand werden Ihre Eingaben an Web3Forms übermittelt, verarbeitet und an uns weitergeleitet. Web3Forms gibt an, Formulardaten nicht dauerhaft zu speichern; technische Protokolle können zeitlich begrenzt verarbeitet werden. Die Verarbeitung kann außerhalb der EU stattfinden. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO beziehungsweise Ihre Einwilligung.</p><p>Die Formularintegration verwendet ein öffentliches Formular-Kennzeichen, ein unsichtbares Botfeld, Zeitprüfung und lokale Ratenbegrenzung. Eine Domainbeschränkung wird im Web3Forms-Konto verwaltet.</p><h2>4. WhatsApp</h2><p>Eine Verbindung zu WhatsApp entsteht erst, wenn Sie einen WhatsApp-Link öffnen. Den vorbereiteten Text prüfen und senden Sie selbst.</p><h2>5. Google-Bewertungen und Statistik</h2><p>Aktuelle Bewertungen können über Google Maps Platform geladen werden. Optionale Reichweitenmessung wird erst nach Ihrer Zustimmung aktiviert. Ihre Auswahl kann lokal gespeichert werden.</p><h2>6. Ihre Rechte</h2><p>Sie haben nach den gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch.</p></>}}[slug as 'impressum'|'agb'|'datenschutz'];if(!data)notFound();return <><Breadcrumbs label={data.title}/><section className="page-intro-next section"><div className="container narrow-next"><p className="eyebrow">RECHTLICHE INFORMATIONEN</p><h1>{data.title}</h1></div></section><section className="section"><div className="container narrow-next legal-next">{data.body}</div></section></>}

export function InternalPage({slug}:{slug:string}){let content;if(servicePages.some(x=>x.slug===slug))content=<ServicePage slug={slug}/>;else if(slug.startsWith('moebelmontage-'))content=<RegionPage slug={slug.replace('moebelmontage-','')}/>;else content=slug==='leistungen'?<ServicesOverview/>:slug==='regionen'?<RegionsOverview/>:slug==='gewerbekunden'?<PartnerPage/>:slug==='referenzen'?<ReferencesPage/>:slug==='ueber-uns'?<AboutPage/>:slug==='kontakt'?<ContactPage/>:['impressum','datenschutz','agb'].includes(slug)?<LegalPage slug={slug}/>:notFound();return <><Header/><main id="main">{content}</main><Footer/></>}
