import { cpSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

// Create responsive WebP variants before any page references them.
execFileSync(process.execPath, ['scripts/optimize-images.mjs'], { stdio: 'inherit' });

// All routes are generated by the Next.js App Router. Recreate public so stale
// HTML from the retired generator cannot shadow a Next.js route.
rmSync('public', { recursive: true, force: true });
mkdirSync('public', { recursive: true });
cpSync('assets', join('public', 'assets'), { recursive: true });
cpSync('favicon.svg', 'public/favicon.svg');
